### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by devnhanhoa** [devnhanhoa/ngx-web4s#1]
Code breadcrumbs dùng chung cho các màn hình
![untitled](https://user-images.githubusercontent.com/34637119/34247149-1084ec18-e664-11e7-9dc9-ecaecf62deae.png)

**Comment by hungcuongqn86** [comment]
@ngannk, anh nghĩ em cần input vào 1 mảng mà mỗi phần tử có lable và url!

**Comment by ngannk** [comment]
@hungcuongqn86 anh ơi, muốn console log data trong typescript thì thực hiện như thế nào ạ, em đang mắc ở chỗ không thấy hiển thị dữ liệu breadcumb mặc dù không thấy báo lỗi gì hết ạ

**Comment by hungcuongqn86** [comment]
em sử dụng console.log như trong js bình thường đc mà

**Comment by devnhanhoa** [comment]
@dvtruongbk

**Comment by hungcuongqn86** [comment]
@ngannk , không cần auto breadcrumbs  theo route, em sửa theo cách truyền biến input vào như anh trao đổi nhé, cách xử lý của em cũng rất hay nhưng hơi phức tạp và anh nghĩ rằng sẽ khó khăn cho việc customize, xử lý đơn giản thôi nhé...

**Comment by hungcuongqn86** [comment]
@ngannk 
em làm đúng hướng rồi
mảng truyền vào em them url để redirect khi click vào nữa là ok
em cứ kiểm tra nếu phần tử mảng có url thì khi nhấn vào thì redirect còn nếu url null hoặc = '' thì không redirect
còn đâu tại các màn hình khi truyền vào sẽ chủ động đặt url cho phù hợp
sau đó em set cho các màn hình danh sách và chi tiết sản phẩm và đơn hang nhé

**Comment by hungcuongqn86** [comment]
@ngannk Cái này chiều nay em xử lý xong đi nhé!
